import * as THREE from 'three'; import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x1b0b38); scene.fog=new THREE.FogExp2(0x35134f,.018);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,220); const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.7)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.outputColorSpace=THREE.SRGBColorSpace; document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xd9a8ff,0x30103f,2.0)); const moon=new THREE.DirectionalLight(0xffc8ef,2.6); moon.position.set(-10,18,8); moon.castShadow=true; scene.add(moon);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(120,180),new THREE.MeshStandardMaterial({color:0x35184a,roughness:1})); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; scene.add(ground);
const road=new THREE.Mesh(new THREE.PlaneGeometry(10,145),new THREE.MeshStandardMaterial({color:0x8b3d82,roughness:.9})); road.rotation.x=-Math.PI/2; road.position.y=.015; scene.add(road);
const player=new THREE.Group(); scene.add(player); player.position.set(0,0,55);
// fallback Lelinha always available
const body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.15,6,10),new THREE.MeshStandardMaterial({color:0xc75aa7})); body.position.y=1.15; body.castShadow=true; player.add(body); const head=new THREE.Mesh(new THREE.SphereGeometry(.52,16,12),new THREE.MeshStandardMaterial({color:0xf1b99f})); head.position.y=2.25; player.add(head); const hair=new THREE.Mesh(new THREE.SphereGeometry(.56,16,12,0,Math.PI*2,0,Math.PI*.7),new THREE.MeshStandardMaterial({color:0x09070d})); hair.position.set(0,2.35,-.06); player.add(hair);
// glasses
const gm=new THREE.MeshStandardMaterial({color:0x181020}); for(const x of [-.23,.23]){const g=new THREE.Mesh(new THREE.TorusGeometry(.19,.035,6,14),gm);g.position.set(x,2.28,.48);player.add(g)} const bridge=new THREE.Mesh(new THREE.BoxGeometry(.16,.035,.035),gm);bridge.position.set(0,2.28,.48);player.add(bridge);
const loader=new GLTFLoader(); let loaded=0; const total=5; function prog(){loaded++; document.querySelector('#bar').style.width=(Math.min(loaded,total)/total*100)+'%';if(loaded>=total)setTimeout(()=>document.querySelector('#loading').style.display='none',300)}; setTimeout(()=>{document.querySelector('#loading').style.display='none'},10000)
// Try real base character; if textures/model incompatibility, fallback remains
loader.load('assets/character/lelinha.gltf',g=>{const m=g.scene;m.scale.setScalar(1.05);m.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}}); body.visible=head.visible=hair.visible=false; player.add(m); prog()},e=>{},()=>prog());
const assetCache={}; async function asset(name){if(assetCache[name])return assetCache[name].clone(); return new Promise(res=>loader.load('assets/graveyard/'+name+'.glb',g=>{assetCache[name]=g.scene;prog();res(g.scene.clone())},undefined,()=>{prog();res(null)}))}
function simpleTree(x,z,s=1){const t=new THREE.Group(); const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.2,.35,2,7),new THREE.MeshStandardMaterial({color:0x4c2449}));trunk.position.y=1;t.add(trunk);const crown=new THREE.Mesh(new THREE.SphereGeometry(1.2,10,8),new THREE.MeshStandardMaterial({color:0xe15aaf}));crown.position.y=2.5;crown.scale.y=1.35;t.add(crown);t.position.set(x,0,z);t.scale.setScalar(s);scene.add(t)}
for(let z=-60;z<62;z+=8){simpleTree(-8-Math.random()*5,z, .8+Math.random()*.5);simpleTree(8+Math.random()*5,z,.8+Math.random()*.5)}
for(const [n,poses] of Object.entries({'pumpkin-carved':[[-5,48],[5,35],[-6,18],[6,-4],[-5,-30]],'gravestone-round':[[-7,10],[7,3],[-7,-18],[7,-25]],'character-ghost':[[-5,25],[5,-12],[-4,-42]],'crypt-large':[[0,-64]]})) asset(n).then(base=>{if(!base)return;for(const [x,z] of poses){const o=base.clone();o.position.set(x,0,z);o.scale.setScalar(n==='character-ghost'?1.2:1.0);scene.add(o);if(n==='character-ghost')ghosts.push(o)}});
const stars=[],ghosts=[]; for(let i=0;i<12;i++){const geo=new THREE.OctahedronGeometry(.38);const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0xffdf55,emissive:0xff8a22,emissiveIntensity:1.4}));m.position.set((i%2?2.2:-2.2)+(Math.random()-.5)*2,1.1,48-i*9.2);scene.add(m);stars.push(m)}
// portal
const portal=new THREE.Mesh(new THREE.TorusGeometry(2.3,.28,12,40),new THREE.MeshStandardMaterial({color:0xff79d1,emissive:0xa819ff,emissiveIntensity:2}));portal.position.set(0,2.6,-56);scene.add(portal); const pLight=new THREE.PointLight(0xff55cc,18,14);pLight.position.copy(portal.position);scene.add(pLight);
const keys={}; addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault()},{passive:false});addEventListener('keyup',e=>keys[e.code]=false);
let joyX=0,joyY=0,joyPointer=null; const joy=document.querySelector('#joystick'),knob=document.querySelector('#knob');
function updateJoy(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=e.clientX-cx,y=e.clientY-cy,max=r.width*.34,d=Math.hypot(x,y)||1;if(d>max){x=x/d*max;y=y/d*max}joyX=x/max;joyY=y/max;knob.style.transform=`translate(${x}px,${y}px)`}
joy.addEventListener('pointerdown',e=>{joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);updateJoy(e);e.preventDefault()});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)updateJoy(e)});function resetJoy(e){if(e.pointerId!==joyPointer)return;joyPointer=null;joyX=joyY=0;knob.style.transform='translate(0,0)'}joy.addEventListener('pointerup',resetJoy);joy.addEventListener('pointercancel',resetJoy);
const jump=document.querySelector('#jump');jump.addEventListener('pointerdown',e=>{keys.Space=true;jump.setPointerCapture(e.pointerId);e.preventDefault()});['pointerup','pointercancel'].forEach(ev=>jump.addEventListener(ev,()=>keys.Space=false));
let camYaw=0,camPitch=.18,camPointer=null,lastPX=0,lastPY=0;renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&e.clientX>innerWidth*.36){camPointer=e.pointerId;lastPX=e.clientX;lastPY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)}});renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerId!==camPointer)return;camYaw-=(e.clientX-lastPX)*.006;camPitch=THREE.MathUtils.clamp(camPitch-(e.clientY-lastPY)*.004,-.12,.48);lastPX=e.clientX;lastPY=e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(e.pointerId===camPointer)camPointer=null});
let vy=0,onGround=true,score=0,won=false; const clock=new THREE.Clock(); function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.035);let dx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+joyX,dz=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0)+joyY;const l=Math.hypot(dx,dz)||1;dx/=l;dz/=l;const speed=6.2;player.position.x+=dx*speed*dt;player.position.z+=dz*speed*dt;player.position.x=THREE.MathUtils.clamp(player.position.x,-5.3,5.3);player.position.z=THREE.MathUtils.clamp(player.position.z,-61,58);if(dx||dz)player.rotation.y=Math.atan2(dx,dz);if((keys.Space)&&onGround){vy=7.3;onGround=false;keys.Space=false}vy-=18*dt;player.position.y+=vy*dt;if(player.position.y<=0){player.position.y=0;vy=0;onGround=true}
for(const s of stars){if(!s.visible)continue;s.rotation.y+=dt*2;s.position.y=1.1+Math.sin(performance.now()*.003+s.position.z)*.15;if(s.position.distanceTo(player.position)<1.35){s.visible=false;score++;document.querySelector('#score').textContent=score}}
for(const g of ghosts){g.position.y=.5+Math.sin(performance.now()*.002+g.position.z)*.45;g.rotation.y+=dt*.35}
if(!won&&player.position.distanceTo(portal.position)<3.1){won=true;document.querySelector('#msg').innerHTML=score>=8?'✨ Portal aberto! Fase 1 concluída! ✨':'O portal pede pelo menos 8 estrelas!';if(score<8)setTimeout(()=>won=false,1800)}
const target=player.position.clone().add(new THREE.Vector3(Math.sin(camYaw)*7.2,3.0+camPitch*3,Math.cos(camYaw)*7.2));camera.position.lerp(target,1-Math.pow(.001,dt));camera.lookAt(player.position.x,player.position.y+1.5,player.position.z-2.2);renderer.render(scene,camera)}loop();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});

document.addEventListener('contextmenu',e=>e.preventDefault());
