import * as T from 'three';
import {AdventureSystem} from '../src/adventure.js';
export function install(api){
 const panel=document.createElement('section');panel.id='qa-v44';panel.style='position:fixed;bottom:0;left:0;z-index:999;background:#130b20e8;color:white;max-height:45vh;overflow:auto;width:min(620px,100vw);font:12px monospace;padding:8px';panel.innerHTML='<button id="qa-run">Executar regressão v44</button><button id="qa-hide">Ocultar painel</button><pre id="qa-results">Pronto</pre>';document.body.append(panel);if(new URLSearchParams(location.search).has('responsive'))panel.hidden=true;panel.querySelector('#qa-hide').onclick=()=>panel.hidden=true;panel.querySelector('#qa-run').onclick=run;
 const results=[],out=panel.querySelector('pre'),wait=ms=>new Promise(r=>setTimeout(r,ms));
 async function until(predicate,timeout=5000){const end=performance.now()+timeout;while(!predicate()&&performance.now()<end)await wait(40);return predicate()}
 function check(name,pass,detail=null){results.push({name,pass:!!pass,detail,state:api.get().state});out.textContent=JSON.stringify(results,null,2)}
 async function run(){panel.querySelector('#qa-run').disabled=true;const faults=[];const error=e=>faults.push(e.message||String(e.reason));window.addEventListener('error',error);window.addEventListener('unhandledrejection',error);try{
  const story=new AdventureSystem(new T.Scene(),'qa-v44');story.stage=0;story.update(90,new T.Vector3());story.start();story.update(1,new T.Vector3());check('Perseguição inicia seu próprio cronômetro',story.stage===1&&story.timer===1);story.update(28,new T.Vector3());check('Fragmento da rival é coletável uma vez',story.stage===2&&story.fragment.visible&&story.interact(new T.Vector3())&&story.stage===3&&!story.fragment.visible&&!story.interact(new T.Vector3()));story.dispose();localStorage.removeItem('wf-story-qa-v44');
  api.goToMenu();api.selectPhase('floresta');let g=api.get();check('Hero, animações e biblioteca Kenney completos',g.assets.lelinha&&g.assets.heroAnimations.length>20&&Object.keys(g.assets.kenney).length===23,{animations:g.assets.heroAnimations.length,kenney:Object.keys(g.assets.kenney).length});
  api.start();await api.get().creatureModelsV34.ready;g=api.get();check('Partida fecha menu e cria apenas um HUD',g.state==='playing'&&document.getElementById('menu').classList.contains('hidden')&&document.querySelectorAll('#gamer-hud-v34').length===1);
  check('Deer e Bat carregam e possuem animações',g.creatureModelsV34.loaded.length===2&&g.creatureModelsV34.mixers.length===2);
  const wasTouch=g.input.touch,wasFloating=g.input.floating;g.input.touch=true;g.input.floating=true;api.pause();api.resume();const stick=document.getElementById('stick');const visibleStick=()=>{const r=stick.getBoundingClientRect();return r.width>0&&r.height>0&&r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight&&!document.getElementById('touch').classList.contains('hidden')};
  let sr=stick.getBoundingClientRect();const pointer=(type,x,y,id=97)=>stick.dispatchEvent(new PointerEvent(type,{pointerId:id,clientX:x,clientY:y,bubbles:true,pointerType:'touch'}));pointer('pointerdown',sr.left+sr.width/2,sr.top+sr.height/2);pointer('pointermove',sr.left+sr.width/2+35,sr.top+sr.height/2-35);check('Joystick flutuante movimenta dois eixos',g.input.axis.x>0&&g.input.axis.y<0);pointer('pointerup',0,0);check('Soltar joystick mantém base visível e zera eixos',visibleStick()&&g.input.axis.x===0&&g.input.axis.y===0);
  sr=stick.getBoundingClientRect();pointer('pointerdown',sr.left+20,sr.top+20);pointer('pointercancel',0,0);check('Cancelar toque restaura joystick',visibleStick()&&!stick.classList.contains('floating'));pointer('pointerdown',sr.left+20,sr.top+20);g.input.clear();check('Perda de foco limpa captura e restaura joystick',visibleStick()&&!stick.classList.contains('active'));api.pause();api.resume();check('Joystick retorna após pausa',visibleStick());document.getElementById('grimoire-open').click();document.getElementById('grimoire-close').click();check('Joystick retorna após Grimório',visibleStick());document.getElementById('photo-btn').click();check('Modo foto preserva controles e botão de saída',getComputedStyle(document.getElementById('touch')).opacity!=='0'&&getComputedStyle(document.querySelector('.final-tools')).opacity!=='0');document.getElementById('photo-btn').click();g.input.touch=wasTouch;g.input.floating=wasFloating;g.input.clear();api.pause();api.resume();
  const before=g.flight.position.clone();g.input.keys.add('KeyW');g.input.keys.add('ArrowUp');await until(()=>g.flight.position.distanceTo(before)>3&&g.flight.position.y>before.y+1);g.input.clear();check('Movimento e subida no loop real',g.flight.position.distanceTo(before)>2&&g.flight.position.y>before.y);
  api.magic();check('Magia cria projétil e consome MP',g.creatureCombatV35.projectiles.length>0&&g.playerVitals.magic<100);const shots=g.creatureCombatV35.projectiles.length;api.magic();check('Cooldown impede disparo duplicado',g.creatureCombatV35.projectiles.length===shots);
  g.flight.position.set(0,2,90);g.flight.speed=0;const landed=g.flight.land();check('Pouso e montagem usam terreno real',landed&&g.flight.grounded&&g.flight.mount()&&!g.flight.grounded);
  g.magicSystem.index=2;g.magicSystem.cast(g.flight);await until(()=>g.playerVitals.invuln>0);const shieldHp=g.playerVitals.health;check('Aegis realmente bloqueia dano',!g.playerVitals.damage(10)&&g.playerVitals.health===shieldHp);g.flight.shieldTime=0;g.playerVitals.invuln=0;g.magicSystem.index=1;g.flight.energy=40;g.magicSystem.cast(g.flight);check('Ventus recupera energia',g.flight.energy===58);g.magicSystem.index=3;const blink=g.flight.position.clone();g.magicSystem.cast(g.flight);check('Blink desloca personagem',g.flight.position.distanceTo(blink)>2);g.magicSystem.index=0;
  api.pause();const frozen={elapsed:api.get().elapsed,position:g.flight.position.clone(),magic:g.playerVitals.magic};await wait(600);check('Pausa congela tempo, posição e MP',api.get().elapsed===frozen.elapsed&&g.flight.position.equals(frozen.position)&&g.playerVitals.magic===frozen.magic);api.resume();
  // Projectile collision and rewards through live combat, not direct death flags.
  const target=g.creatureCombatV35.entities[0];target.object.position.copy(g.flight.position).add(new T.Vector3(0,0,-2));const xp=g.progression.xp;for(let i=0;i<3&&!target.dead;i++){await until(()=>target.invuln===0);const hp=target.hp;g.creatureCombatV35.cast(target.object.position.clone().add(new T.Vector3(0,0,1)),new T.Vector3(0,0,-1),20);await until(()=>target.hp<hp)}await until(()=>target.dead&&g.progression.xp===xp+target.xp);
  check('Projétil mata criatura e credita XP uma vez',target.dead&&g.progression.xp===xp+target.xp,{hp:target.hp,xp:g.progression.xp});check('Derrota gera loot físico',g.lootV36.items.length===1);
  const item=g.lootV36.items[0],ess=api.get().essence;if(item){g.flight.position.copy(item.m.position);g.flight.speed=0;await until(()=>api.get().essence>ess)}check('Coleta de loot credita essência',api.get().essence>ess&&g.lootV36.items.length===0);
  g.respawnV36.set(new T.Vector3(0,7,90),'floresta');g.playerVitals.health=0;await until(()=>g.playerVitals.health===100);check('Morte restaura HP e ponto seguro',g.playerVitals.health===100&&g.flight.position.distanceTo(new T.Vector3(0,7,90))<2);
  g.exploration.toggleVision();check('Visão Mágica é compartilhada com exploração profunda',g.exploration.vision===g.exploration.active);const site=g.deepExploration.sites[0];g.deepExploration.interact(site.g.position,false);g.deepExploration.interact(site.g.position,true);check('Investigação avança com Visão Mágica',site.stage>=2);
  g.missions.step=2;g.missions.rings=3;g.exploration.points[0].found=true;
  g.flight.position.set(12,18,75);g.playerVitals.magic=0;api.saveSession();api.goToMenu();await api.continueSession();g=api.get();api.pause();check('Continuar restaura posição e MP zero',g.flight.position.distanceTo(new T.Vector3(12,18,75))<1&&g.playerVitals.magic<1);check('Save restaura missão, descobertas e inimigo derrotado',g.missions.step===2&&g.exploration.points[0].found&&g.creatureCombatV35.entities[0].dead);check('Reinício não duplica HUD e raízes de criaturas',document.querySelectorAll('#gamer-hud-v34').length===1&&g.world.scene.children.filter(x=>x.name==='RealCreatures-v34').length===1);
  api.goToMenu();api.selectPhase('vila');api.start();await api.get().creatureModelsV34.ready;g=api.get();check('Vila reconstrói cenário e Deer',g.world.phaseId==='vila'&&g.creatureModelsV34.loaded.length===1);await wait(300);
  api.goToMenu();api.selectPhase('castelo');api.start();await api.get().creatureModelsV34.ready;g=api.get();check('Castelo carrega Ghost, Bat e Cyclops',g.creatureModelsV34.loaded.length===3&&!!g.bossCyclopsV35.entity);api.pause();
  const boss=g.bossCyclopsV35.entity,enc=g.cyclopsEncounterV38;const center=boss.object.position.clone();enc.state='idle';enc.timer=0;let ev=enc.update(.01,center);check('Cyclops entra em telegraph',ev?.type==='telegraph');ev=enc.update(.9,center);const hp=g.playerVitals.health;g.playerVitals.invuln=0;const hit=enc.resolve(ev,center);check('Strike aplica dano uma única vez',ev?.type==='strike'&&hit&&g.playerVitals.health<hp&&!enc.resolve(ev,center));check('Strike termina em recovery',enc.update(.3,center)?.type==='recover');
  boss.hp=100;g.bossCyclopsV35.update(.01);check('Cyclops fase 2 por HP',g.bossCyclopsV35.phase===2);boss.hp=30;g.bossCyclopsV35.update(.01);check('Cyclops fase 3 por HP',g.bossCyclopsV35.phase===3);enc.state='telegraph';enc.timer=0;ev=enc.update(.01,center);check('Fase 3 amplia ataque e permite esquiva',ev.radius===3.2&&!enc.resolve(ev,center.clone().add(new T.Vector3(10,0,0))));
  const deadAgent=g.creatureAI.agents.find(a=>a.object===boss.object);boss.dead=true;const old=deadAgent.object.position.clone();g.creatureAI.update(1,center.clone().add(new T.Vector3(5,0,0)));check('Criatura morta não continua IA',old.equals(deadAgent.object.position));
  const entry=g.dungeonAdventure.entry.position;g.dungeonAdventure.update(.1,entry);for(const rune of g.dungeonAdventure.runes)g.dungeonAdventure.update(.1,rune.m.position);check('Masmorra completa as três runas',g.dungeonAdventure.done&&g.dungeonAdventure.runes.every(r=>r.found));
  for(const mode of ['low','medium','high']){g.graphicsProfile.apply(mode);api.resize();check('Qualidade '+mode+' aplica limite de resolução',g.renderer.getPixelRatio()<=(mode==='low'?.85:mode==='medium'?1.15:1.5)+.001,{dpr:g.renderer.getPixelRatio()})}
  api.saveSession();check('Save contém runas e fase',JSON.parse(localStorage.getItem('lelinha-save')).session.dungeon.done);
  g.settingsV39.data.particles=.3;g.settingsV39.save();g.settingsV39.apply();g.accessibilityV41.data.reducedFlashes=true;g.accessibilityV41.apply();await wait(100);check('Reduzir flashes desativa partículas ambiente',g.world.fireflies.geometry.drawRange.count===0);g.accessibilityV41.data.reducedFlashes=false;g.accessibilityV41.apply();
  api.resume();const times=[];await new Promise(resolve=>{let prev=performance.now();const step=t=>{times.push(t-prev);prev=t;if(times.length<90)requestAnimationFrame(step);else resolve()};requestAnimationFrame(step)});times.sort((a,b)=>a-b);check('Profiling de 90 frames concluído',true,{medianMs:times[45],p95Ms:times[85],drawCalls:g.renderer.info.render.calls,triangles:g.renderer.info.render.triangles,geometries:g.renderer.info.memory.geometries,textures:g.renderer.info.memory.textures});
  api.finish();check('Fim de ritual abre resultado',api.get().state==='result'&&!document.getElementById('result').classList.contains('hidden'));api.goToMenu();
  check('Sessão sem exceções JavaScript',faults.length===0,faults);
 }catch(e){check('Execução completa sem exceção',false,e.stack)}finally{const summary={passed:results.filter(r=>r.pass).length,total:results.length,results};out.textContent=JSON.stringify(summary,null,2);document.title=`QA v44: ${summary.passed}/${summary.total}`;const a=document.createElement('a');a.textContent='Baixar resultados JSON';a.download='QA-v44.json';a.href=URL.createObjectURL(new Blob([JSON.stringify(summary,null,2)],{type:'application/json'}));panel.append(a);try{if(location.port==='4176')await fetch('/__qa/results',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(summary)})}catch{}window.removeEventListener('error',error);window.removeEventListener('unhandledrejection',error)}}
}
