import {storage} from './storage.js';
import * as T from 'three';
export class AdventureSystem{
 constructor(scene,phase='floresta'){this.scene=scene;this.phase=phase;this.stage=Number(storage.getItem('wf-story-'+phase)||0);this.rival=null;this.timer=0;this.makeRival();this.fragment=new T.Mesh(new T.OctahedronGeometry(.5),new T.MeshStandardMaterial({color:0xffa5ed,emissive:0xff4bcc,emissiveIntensity:1}));this.fragment.visible=false;this.fragmentPlaced=false;this.scene.add(this.fragment)}
 makeRival(){const g=new T.Group(),cloth=new T.MeshStandardMaterial({color:0x7a286f,roughness:.72,emissive:0x220c25,emissiveIntensity:.22}),skin=new T.MeshStandardMaterial({color:0xe9b59e,roughness:.82}),dark=new T.MeshStandardMaterial({color:0x301335,roughness:.8}),wood=new T.MeshStandardMaterial({color:0x6a3d25,roughness:.92});const torso=new T.Mesh(new T.CapsuleGeometry(.27,.55,4,8),cloth);torso.position.set(0,.72,0);torso.rotation.x=.28;g.add(torso);const head=new T.Mesh(new T.SphereGeometry(.27,12,9),skin);head.position.set(0,1.32,-.08);g.add(head);const brim=new T.Mesh(new T.CylinderGeometry(.38,.38,.045,16),dark);brim.position.set(0,1.56,-.08);g.add(brim);const hat=new T.Mesh(new T.ConeGeometry(.25,.62,14),dark);hat.position.set(.04,1.88,-.08);hat.rotation.z=-.14;g.add(hat);const broom=new T.Mesh(new T.CylinderGeometry(.045,.055,2.35,7),wood);broom.rotation.z=Math.PI/2;broom.position.set(0,.35,0);g.add(broom);for(const side of [-1,1]){const leg=new T.Mesh(new T.CapsuleGeometry(.07,.48,3,6),dark);leg.position.set(side*.18,.28,.22);leg.rotation.x=1.05;leg.rotation.z=side*.18;g.add(leg)}g.rotation.x=-.06;g.visible=false;this.scene.add(g);this.rival=g}
 start(){if(this.stage===0){this.stage=1;this.timer=0;this.persist();this.rival.visible=true;return'A rival mascarada apareceu · siga o rastro violeta'}return null}
 update(dt,pos){if(this.stage===1){this.timer+=dt;this.rival.visible=true;const a=this.timer*.42;this.rival.position.set(pos.x+Math.cos(a)*10,pos.y+3+Math.sin(a*1.7)*2,pos.z-14+Math.sin(a)*8);this.rival.lookAt(pos);if(this.timer>28){this.stage=2;this.rival.visible=false;this.persist();this.placeFragment(pos);return'PERSEGUIÇÃO CONCLUÍDA · a rival deixou um fragmento lunar'}}if(this.stage===2){if(!this.fragmentPlaced)this.placeFragment(pos);this.fragment.rotation.y+=dt;this.fragment.rotation.z+=dt*.3}return null}
 placeFragment(pos){this.fragment.position.copy(pos).add(new T.Vector3(2,0,0));this.fragment.visible=true;this.fragmentPlaced=true}
 nearest(pos){return this.stage===2&&this.fragmentPlaced&&this.fragment.position.distanceTo(pos)<4}
 interact(pos){if(pos&&this.nearest(pos)){this.stage=3;this.fragment.visible=false;this.persist();return'FRAGMENTO LUNAR RECUPERADO · novo capítulo registrado'}return null}
 persist(){storage.setItem('wf-story-'+this.phase,String(this.stage))}
 dispose(){this.scene.remove(this.fragment);this.fragment.geometry.dispose();this.fragment.material.dispose();this.scene.remove(this.rival);this.rival?.traverse(o=>{o.geometry?.dispose?.();o.material?.dispose?.()})}
}
