import {storage} from './storage.js';
export class Input {
  constructor() {
    this.keys=new Set(); this.actions={}; this.axis={x:0,y:0}; this.tilt={x:0,y:0}; this.look={x:0,y:0};
    this.tiltEnabled=false; this.tiltCalibrated=false; this.tiltCenter={beta:0,gamma:0};
    this.magicPressed=false; this.modePressed=false; this.interactPressed=false; this.visionPressed=false; this.cameraPressed=false; this.vehiclePressed=false;
    this.touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0||innerWidth<760;
    this.enabled=false; this.lastDevice=this.touch?'touch':'keyboard'; this.gamepadIndex=null; this._gpPrev=[];
    this.sensitivityX=Number(storage.getItem('wf-sens-x')||storage.getItem('wf-sensitivity')||1);
    this.sensitivityY=Number(storage.getItem('wf-sens-y')||storage.getItem('wf-sensitivity')||1);
    this.sensitivity=(this.sensitivityX+this.sensitivityY)/2;
    this.invertY=storage.getItem('wf-invert-y')==='1';
    this.floating=storage.getItem('wf-floating-stick')!=='0';
    this.leftHanded=storage.getItem('wf-left-handed')==='1';
    this.assist=storage.getItem('wf-assist')||'normal';
    this.motion=Number(storage.getItem('wf-motion')??.55);
    this.controlScale=Number(storage.getItem('wf-control-scale')||1);
    this.controlOpacity=Number(storage.getItem('wf-control-opacity')||.92);
    this.haptics=storage.getItem('wf-haptics')!=='0';
    this.applyUISettings();

    window.addEventListener('keydown',e=>{this.lastDevice='keyboard';if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)&&this.enabled)e.preventDefault();if((e.code==='Space'||e.code==='KeyK')&&!e.repeat)this.magicPressed=true;if(e.code==='KeyC'&&!e.repeat)this.modePressed=true;if(e.code==='KeyE'&&!e.repeat)this.interactPressed=true;if(e.code==='KeyV'&&!e.repeat)this.visionPressed=true;if(e.code==='KeyB'&&!e.repeat)this.vehiclePressed=true;this.keys.add(e.code)});
    window.addEventListener('keyup',e=>this.keys.delete(e.code)); window.addEventListener('blur',()=>this.clear());
    document.addEventListener('visibilitychange',()=>{if(document.hidden)this.clear()}); if(this.touch)document.body.classList.add('touch-mode');
    document.querySelectorAll('[data-action]').forEach(b=>{const action=b.dataset.action;const on=e=>{e.preventDefault();this.lastDevice='touch';try{b.setPointerCapture(e.pointerId)}catch{};this.actions[action]=true;if(action==='magic')this.magicPressed=true;if(action==='mode')this.modePressed=true;if(action==='interact')this.interactPressed=true;if(action==='vision')this.visionPressed=true;if(action==='camera')this.cameraPressed=true;if(action==='vehicle')this.vehiclePressed=true};const off=()=>{this.actions[action]=false};b.addEventListener('pointerdown',on);for(const n of ['pointerup','pointercancel','lostpointercapture','pointerleave'])b.addEventListener(n,off)});

    const stick=document.querySelector('#stick'),thumb=document.querySelector('#stick-thumb'); let active=null,center={x:0,y:0}; const radius=52;
    const place=e=>{if(this.floating){const half=stick.offsetWidth*this.controlScale/2;center={x:Math.max(half,Math.min(innerWidth-half,e.clientX)),y:Math.max(half,Math.min(innerHeight-half,e.clientY))};stick.classList.add('floating','active');stick.style.left=(center.x-half)+'px';stick.style.top=(center.y-half)+'px';stick.style.right='auto';stick.style.bottom='auto';stick.style.transform='scale('+this.controlScale+')';stick.style.transformOrigin='top left'}else{const r=stick.getBoundingClientRect();center={x:r.left+r.width/2,y:r.top+r.height/2};stick.classList.remove('floating')}};
    const move=e=>{if(active!==e.pointerId)return;this.lastDevice='touch';let x=(e.clientX-center.x)/radius,y=(e.clientY-center.y)/radius;let m=Math.hypot(x,y);if(m>1){x/=m;y/=m;m=1}const dead=.12;if(m<dead){this.axis={x:0,y:0};thumb.style.transform='translate(0,0)';return}const scaled=(m-dead)/(1-dead),curve=scaled*scaled*(3-2*scaled);x=x/m*curve;y=y/m*curve;this.axis={x,y};thumb.style.transform=`translate(${x*42}px,${y*42}px)`};
    stick.addEventListener('pointerdown',e=>{if(!this.enabled||active!==null)return;active=e.pointerId;place(e);try{stick.setPointerCapture(active)}catch{};move(e)});stick.addEventListener('pointermove',move);
    this.resetStick=()=>{const id=active;active=null;if(id!==null&&stick.hasPointerCapture?.(id))stick.releasePointerCapture(id);this.axis={x:0,y:0};thumb.style.transform='';stick.classList.remove('active','floating');for(const name of ['left','top','right','bottom','transform','transform-origin'])stick.style.removeProperty(name)};
    for(const n of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(n,e=>{if(active===null||e.pointerId===active)this.resetStick()});
    document.addEventListener('pointerdown',e=>{const leftRegion=this.leftHanded?e.clientX>innerWidth*.52:e.clientX<innerWidth*.48;if(!this.enabled||!this.touch||!this.floating||active!==null||!leftRegion||e.target.closest('button,input,select,label'))return;active=e.pointerId;place(e);try{stick.setPointerCapture(active)}catch{};move(e)},{passive:false});

    // Right-side drag camera; in left-handed mode the look zone moves to the left.
    let lookId=null,last={x:0,y:0};
    document.addEventListener('pointerdown',e=>{const lookRegion=this.leftHanded?e.clientX<innerWidth*.48:e.clientX>innerWidth*.52;if(!this.enabled||!this.touch||!lookRegion||e.target.closest('button,input,select,label,#stick'))return;lookId=e.pointerId;last={x:e.clientX,y:e.clientY};this.lastDevice='touch'},{passive:true});
    document.addEventListener('pointermove',e=>{if(e.pointerId!==lookId)return;const dx=e.clientX-last.x,dy=e.clientY-last.y;last={x:e.clientX,y:e.clientY};this.look.x=Math.max(-1,Math.min(1,this.look.x+dx/110));this.look.y=Math.max(-1,Math.min(1,this.look.y+dy/110))},{passive:true});
    this.resetLook=()=>{lookId=null};
    const endLook=e=>{if(e.pointerId===lookId)lookId=null}; document.addEventListener('pointerup',endLook);document.addEventListener('pointercancel',endLook);

    this._onOrientation=e=>{if(!this.tiltEnabled||!this.enabled)return;const beta=e.beta??0,gamma=e.gamma??0;if(!this.tiltCalibrated){this.tiltCenter={beta,gamma};this.tiltCalibrated=true}this.tilt={x:Math.max(-1,Math.min(1,(gamma-this.tiltCenter.gamma)/28)),y:Math.max(-1,Math.min(1,(beta-this.tiltCenter.beta)/28))}};
    window.addEventListener('gamepadconnected',e=>{this.gamepadIndex=e.gamepad.index;this.lastDevice='gamepad';document.body.dataset.input='gamepad'});
    window.addEventListener('gamepaddisconnected',e=>{if(this.gamepadIndex===e.gamepad.index)this.gamepadIndex=null;this._gpPrev=[];document.body.dataset.input=this.touch?'touch':'keyboard'});
  }
  applyUISettings(){document.documentElement.style.setProperty('--control-scale',String(this.controlScale));document.documentElement.style.setProperty('--control-opacity',String(this.controlOpacity));document.body.classList.toggle('left-handed',this.leftHanded)}
  configure(o={}){if(o.sensitivity!=null){this.sensitivityX=this.sensitivityY=Number(o.sensitivity);this.sensitivity=Number(o.sensitivity);storage.setItem('wf-sensitivity',String(o.sensitivity))}if(o.sensitivityX!=null){this.sensitivityX=Number(o.sensitivityX);storage.setItem('wf-sens-x',String(o.sensitivityX))}if(o.sensitivityY!=null){this.sensitivityY=Number(o.sensitivityY);storage.setItem('wf-sens-y',String(o.sensitivityY))}if(o.invertY!=null){this.invertY=o.invertY;storage.setItem('wf-invert-y',o.invertY?'1':'0')}if(o.floating!=null){this.floating=o.floating;storage.setItem('wf-floating-stick',o.floating?'1':'0')}if(o.leftHanded!=null){this.leftHanded=o.leftHanded;storage.setItem('wf-left-handed',o.leftHanded?'1':'0')}if(o.assist){this.assist=o.assist;storage.setItem('wf-assist',o.assist)}if(o.motion!=null){this.motion=Number(o.motion);storage.setItem('wf-motion',String(o.motion))}if(o.controlScale!=null){this.controlScale=Number(o.controlScale);storage.setItem('wf-control-scale',String(o.controlScale))}if(o.controlOpacity!=null){this.controlOpacity=Number(o.controlOpacity);storage.setItem('wf-control-opacity',String(o.controlOpacity))}if(o.haptics!=null){this.haptics=o.haptics;storage.setItem('wf-haptics',o.haptics?'1':'0')}this.resetStick?.();this.applyUISettings()}
  async enableTilt(){try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){if(await DeviceOrientationEvent.requestPermission()!=='granted')return false}window.addEventListener('deviceorientation',this._onOrientation);this.tiltEnabled=true;this.tiltCalibrated=false;return true}catch{return false}}
  disableTilt(){this.tiltEnabled=false;this.tilt={x:0,y:0};window.removeEventListener('deviceorientation',this._onOrientation)}
  refreshTouch(){this.touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0||innerWidth<760;document.body.classList.toggle('touch-mode',this.touch);this.clear()}
  clear(){this.resetStick?.();this.resetLook?.();this.keys.clear();this.actions={};this.axis={x:0,y:0};this.tilt={x:0,y:0};this.look={x:0,y:0};this.magicPressed=false;this.modePressed=false;this.interactPressed=false;this.visionPressed=false;this.cameraPressed=false;this.vehiclePressed=false}
  pollGamepad(){if(!navigator.getGamepads)return null;const pads=navigator.getGamepads();let gp=this.gamepadIndex!=null?pads[this.gamepadIndex]:null;if(!gp){gp=[...pads].find(Boolean)||null;if(gp)this.gamepadIndex=gp.index}if(!gp)return null;const dz=v=>Math.abs(v)<.14?0:Math.sign(v)*(Math.abs(v)-.14)/.86;const ax=gp.axes||[],btn=gp.buttons||[];const pressed=i=>!!btn[i]?.pressed;const edge=i=>{const v=pressed(i),old=!!this._gpPrev[i];this._gpPrev[i]=v;return v&&!old};if(edge(0))this.interactPressed=true;if(edge(2))this.magicPressed=true;if(edge(4))this.visionPressed=true;if(edge(5))this.modePressed=true;if(edge(9))this.actions.pausePulse=true;const active=Math.abs(ax[0]||0)>.14||Math.abs(ax[1]||0)>.14||Math.abs(ax[2]||0)>.14||Math.abs(ax[3]||0)>.14||btn.some(b=>b.pressed);if(active){this.lastDevice='gamepad';document.body.dataset.input='gamepad'}return{x:dz(ax[0]||0),y:dz(ax[1]||0),lookX:dz(ax[2]||0),lookY:dz(ax[3]||0),boost:pressed(7)||pressed(6),gp}}
  pulse(strong=.35,duration=35){if(!this.haptics)return;try{if(navigator.vibrate)navigator.vibrate(Math.round(duration));const gp=this.pollGamepad()?.gp,act=gp?.vibrationActuator;if(act?.playEffect)act.playEffect('dual-rumble',{duration,strongMagnitude:strong,weakMagnitude:strong*.55}).catch(()=>{})}catch{}}
  consumePause(){const v=!!this.actions.pausePulse;this.actions.pausePulse=false;return v}
  get state(){const gp=this.pollGamepad(),k=this.keys,a=this.actions,iy=this.invertY?-1:1;let x=this.axis.x*this.sensitivityX,y=this.axis.y*this.sensitivityY;if(gp){x+=gp.x*this.sensitivityX;y+=gp.y*this.sensitivityY}const turn=(+k.has('KeyD')-k.has('KeyA'))+x+(this.tiltEnabled?this.tilt.x*.95:0);const throttle=(+k.has('KeyW')-k.has('KeyS'))-y*.45+(this.tiltEnabled?-this.tilt.y*.45:0);const stickLift=this.touch||gp?(-y*iy):0;const lift=Number(!!(k.has('ArrowUp')||a.up))-Number(!!(k.has('ArrowDown')||k.has('KeyQ')||a.down))+stickLift;this.look.x*=.88;this.look.y*=.88;if(gp){this.look.x=Math.max(-1,Math.min(1,this.look.x+gp.lookX*.32));this.look.y=Math.max(-1,Math.min(1,this.look.y+gp.lookY*.32*iy))}return{turn:Math.max(-1.4,Math.min(1.4,turn)),throttle:Math.max(-1.2,Math.min(1.2,throttle)),lift:Math.max(-1.2,Math.min(1.2,lift)),boost:k.has('ShiftLeft')||k.has('ShiftRight')||!!a.boost||!!gp?.boost,lookX:this.look.x,lookY:this.look.y,assist:this.assist,motion:this.motion}}
  consumeMagic(){const v=this.magicPressed;this.magicPressed=false;return v} consumeMode(){const v=this.modePressed;this.modePressed=false;return v} consumeInteract(){const v=this.interactPressed;this.interactPressed=false;return v} consumeVision(){const v=this.visionPressed;this.visionPressed=false;return v} consumeCamera(){const v=this.cameraPressed;this.cameraPressed=false;return v} consumeVehicle(){const v=this.vehiclePressed;this.vehiclePressed=false;return v}
}
