import * as T from 'three';
export class KenneyVFX{
 constructor(scene){this.scene=scene;this.pool=[];this.live=[];this.textures={};this.low=document.body.dataset.graphics==='low';const l=new T.TextureLoader();for(const n of ['fire_01','circle_01','magic_01','smoke_01','star_01','flare_01','spark_01','flame_03']){const t=l.load('./assets/kenney/particles/'+n+'.png');t.colorSpace=T.SRGBColorSpace;this.textures[n]=t}for(let i=0;i<(this.low?36:76);i++){const s=new T.Sprite(new T.SpriteMaterial({map:this.textures.spark_01,color:0xffffff,transparent:true,opacity:0,depthWrite:false,blending:T.AdditiveBlending}));s.visible=false;scene.add(s);this.pool.push(s)}}
 spawn(pos,{tex='spark_01',color=0xffffff,count=12,spread=2,life=.7,size=.7,up=.8}={}){count=Math.floor(Math.min(count,this.low?10:28)*(this.density??1));for(let i=0;i<count;i++){const s=this.pool.pop();if(!s)break;s.material.map=this.textures[tex]||this.textures.spark_01;s.material.color.set(color);s.material.opacity=.9;s.position.copy(pos);s.scale.setScalar(size*(.65+Math.random()*.7));s.visible=true;this.live.push({s,life,max:life,v:new T.Vector3((Math.random()-.5)*spread,Math.random()*up,(Math.random()-.5)*spread)})}}
 magic(kind,pos){const c={lumen:['star_01',0xfff0a8],ventus:['spark_01',0xa8f7ff],aegis:['circle_01',0xc6a8ff],blink:['magic_01',0xff9be8]}[kind]||['magic_01',0xffb0e8];this.spawn(pos,{tex:c[0],color:c[1],count:22,spread:5,life:.85,size:.85,up:2.2})}
 ring(pos,perfect=false){this.spawn(pos,{tex:perfect?'star_01':'flare_01',color:perfect?0xffef9c:0xffd4f1,count:perfect?28:16,spread:4,life:.8,size:perfect?1:.65,up:1.6})}
 dungeon(pos){this.spawn(pos,{tex:'flame_03',color:0xff945e,count:6,spread:.7,life:1.15,size:.55,up:1.4})}
 update(dt){for(let i=this.live.length-1;i>=0;i--){const p=this.live[i];p.life-=dt;p.s.position.addScaledVector(p.v,dt);p.s.material.opacity=Math.max(0,p.life/p.max);p.s.scale.multiplyScalar(1+dt*.5);if(p.life<=0){p.s.visible=false;p.s.material.opacity=0;this.pool.push(p.s);this.live.splice(i,1)}}}
}
